routes/admin.php
<?php

Route::group( ['prefix' => 'admin'], function () {
    Voyager::routes();

    //roles update
    Route::match( ['put', 'patch'], 'my-roles/{role}', 'Voyager\VoyagerRoleController@update' )->name( 'voyager.roles.my-update' );
    //setting
    Route::get( '/websetting', 'Voyager\VoyagerSettingsController@websetting' )->name( 'websetting.index' );

    //summernote
    Route::post( 'summernote', 'Formfield\SummernoteController@upload' );

    //slug
    Route::post( '/check/check-dup-title/', ['uses' => 'CheckduptitleController@checkDupTitle'] )->name( 'check.check-dup-title' );

    Route::post( '/check/check-dup-slug/', ['uses' => 'CheckduptitleController@checkDupSlug'] )->name( 'check.check-dup-slug' );

    //memeber
    Route::get( '/members', 'MemberController@index' )->name( 'voyager.member.index' );
    Route::get( '/members/{id}/edit', 'MemberController@edit' )->name( 'voyager.member.edit' );
    Route::get( '/members/{id}', 'Voyager\VoyagerUserController@show' )->name( 'voyager.member.show' );
    Route::delete( '/members/{$id}', 'MemberController@destroy' )->name( 'voyager.member.destroy' );
    Route::put( '/members/{id}', 'Voyager\VoyagerUserController@update' )->name( 'voyager.member.update' );

    //group member
    Route::get( '/business-group', 'MemberController@businessGroup' )->name( 'voyager.business-group.index' );
    Route::get( '/business-group/{id}', 'MemberController@businessGroupShow' )->name( 'voyager.business-group.show' );
    //log Reader : admin/log-reader
    Route::group(
        [
            'namespace'  => '\Haruncpi\LaravelLogReader\Controllers',
            'middleware' => ['auth'],
        ],
        function () {
            Route::get( config( 'laravel-log-reader.view_route_path' ), 'LogReaderController@getIndex' );
            Route::post( config( 'laravel-log-reader.view_route_path' ), 'LogReaderController@postDelete' );
            Route::get( config( 'laravel-log-reader.api_route_path' ), 'LogReaderController@getLogs' );
        }
    );

    // order
    Route::match( ['post'], '/orders/{status}/{id}', [
        'as'   => 'order.changeStatus',
        'uses' => 'OrderController@changeOrder',
    ] );

    // transection
    Route::match( ['post'], '/transection/withdraw/{status}/{id}', [
        'as'   => 'transection.changeStatus',
        'uses' => 'TransectionController@changeStatus',
    ] );

} );

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::group( ['middleware' => ['referral']], function () {
    Route::get( '/', 'Frontend\MainController@index' )->name( 'home' );

    Route::group( ['middleware' => ['auth']], function () {
        Route::get( '/profile', 'Frontend\ProfileController@index' )->name( 'profile' );
        Route::get( '/profile/business', 'Frontend\ProfileController@business' )->name( 'profile.business' );
        Route::get( '/business/payment', 'Frontend\ProfileController@payment' )->name( 'business.payment' );

    } );

    Route::get( '/profile', 'Frontend\ProfileController@index' )->name( 'profile' );
    Route::get( '/profile/business', 'Frontend\ProfileController@business' )->name( 'profile.business' );
    Route::get( '/business/payment', 'Frontend\ProfileController@payment' )->name( 'business.payment' );
    Route::put( '/profile/{id}', 'Frontend\ProfileController@update' )->name( 'profile.update' );
    Route::put( '/business/update/{id}', 'Frontend\ProfileController@businessupdate' )->name( 'business.update' );

    Route::get( '/page/{slug}', 'Frontend\MainController@show' )->name( 'page' );

    Route::get( '/promotions', 'Frontend\PromotionController@index' )->name( 'promotions.index' );

    Route::get( '/tours', 'Frontend\ToursController@index' )->name( 'tours.index' );
    Route::get( '/tours/{slug}', 'Frontend\ToursController@show' )->name( 'tours.show' );

    Route::get( '/visa', 'Frontend\InsuranceController@visa' )->name( 'visa.index' );
    Route::get( '/visa/{slug}', 'Frontend\InsuranceController@show' )->name( 'visa.show' );

    Route::get( '/insurance', 'Frontend\InsuranceController@index' )->name( 'insurance.index' );
    Route::get( '/insurance/{slug}', 'Frontend\InsuranceController@show' )->name( 'insurance.show' );

    Route::group( ['middleware' => ['auth'], 'namespace' => 'Frontend'], function () {

        Route::group( ['as' => 'tours.'], function () {

            Route::match( ['get'], '/tours/payment/{slug}', [
                'as'   => 'payment',
                'uses' => 'ToursController@payment',
            ] );

            Route::match( ['post'], 'tours/payment/store', [
                'as'   => 'store',
                'uses' => 'OrdersController@store',
            ] );

            Route::match( ['put'], 'tours/payment/{id}/repay', [
                'as'   => 'repay',
                'uses' => 'OrdersController@repay',
            ] );

            Route::match( ['get', 'post'], 'tours/payment/paypal/success', [
                'as'   => 'paypal.success',
                'uses' => 'OrdersController@paypalSuccess',
            ] );

            Route::match( ['get'], 'tours/order/completed', [
                'as'   => 'thank',
                'uses' => 'PageController@thank',
            ] );

            Route::match( ['get'], 'tours/order/fail', [
                'as'   => 'fail',
                'uses' => 'PageController@fail',
            ] );

        } );

        Route::group( ['as' => 'insurance.'], function () {

            Route::match( ['get'], '/insurance/payment/{slug}', [
                'as'   => 'payment',
                'uses' => 'InsuranceController@payment',
            ] );

            Route::match( ['post'], 'insurance/payment/store', [
                'as'   => 'store',
                'uses' => 'InsuranceController@store',
            ] );

        } );

        Route::group( ['as' => 'member.'], function () {

            Route::match( ['get'], '/member/transection', [
                'as'   => 'income',
                'uses' => 'MemberController@income',
            ] );

            Route::match( ['post'], '/member/transection/withdraw', [
                'as'   => 'withdraw',
                'uses' => 'MemberController@withdraw',
            ] );

            Route::match( ['put'], '/member/transection/withdraw/update/{id}', [
                'as'   => 'withdraw.update',
                'uses' => 'MemberController@withdrawUpdate',
            ] );

            Route::match( ['get'], '/member/order', [
                'as'   => 'order',
                'uses' => 'OrdersController@index',
            ] );

            Route::match( ['get'], '/member/order/detail/{id}', [
                'as'   => 'order.detail',
                'uses' => 'OrdersController@show',
            ] );

        } );

    } );

    Route::get( '/cart', 'Frontend\CartController@index' )->name( 'cart.index' );
    Route::get( 'add-to-cart/{id}', 'Frontend\CartController@addToCart' );

    Route::get( '/services', 'Frontend\ServiceController@index' )->name( 'services.index' );
    Route::get( '/services/{slug}', 'Frontend\ServiceController@show' )->name( 'services.show' );

    Route::get( '/articles', 'Frontend\ArticleController@index' )->name( 'articles.index' );
    Route::get( '/articles/{slug}', 'Frontend\ArticleController@show' )->name( 'articles.show' );
    Route::get( '/articles/tag/{slug}', 'Frontend\ArticleController@showTag' )->name( 'articles.tag' );

    Route::get( '/about-us', 'Frontend\AboutusController@index' )->name( 'about-us.index' );

    Route::get( '/contact-us', 'Frontend\ContactController@index' )->name( 'contact-us.index' );
    Route::post( '/contact-us', 'Frontend\ContactController@store' )->name( 'contact-us.store' );

    Route::get( '/facebook/redirect', 'SocialAuthController@redirect' )->name( 'facebook.redirect' );
    Route::get( '/facebook/callback', 'SocialAuthController@callback' );

    Auth::routes();
} );

app/Http/Controllers/Frontend/AboutusController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Banner;
use App\Page;

class AboutusController extends Controller
{
    public function index()
    {
        //get banner home
        $banners = Banner::page('about-us')->get();

        $page  = Page::where('slug', 'about-us')->active()->first();
        if (!$page) {
            abort(404);
        }
        return view('frontend.about-us', compact('page'));
    }
}

app/Http/Controllers/Frontend/ArticleController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Banner;
use App\Post;
use App\Category;
use App\TaggableTag;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;


class ArticleController extends Controller
{
    public function index(Request $request)
    {

        //get banner home
        $banners = Banner::page('article')->get();

        //category
        $categories = Category::all();

        //get post
        $articles = Post::select(DB::raw('posts.*,categories.name'))->published()->publicat()
            ->order();

        $articles = $articles->leftJoin('categories', 'posts.category_id', '=', 'categories.id');

        $category = null;
        if ($request->category) {
            $category = $request->category;
            if ($category != 'all') {
                $articles = $articles->where('categories.slug', '=', $category);
            }
        }
        $articles = $articles->get();


        return view('frontend.articles', compact('articles', 'banners', 'categories', 'category'));
    }

    public function show(Request $request, $slug)
    {   
        //get banner home
        $banners = Banner::where('page', 'article')->get();

        //service
        $article = Post::published()->publicat()->where('slug', $slug)->first();

        if (!$article) {
            abort(404);
        }
        $article->category;

        $post = Post::find($article->id);
        $post->viewer = $post->viewer + 1;
        $post->save();

        //SEO
        $seo = Post::select('seo_title', 'meta_description', 'image')->published()->where('slug', $slug)->first();

        return view('frontend.article-detail', compact('banners', 'article', 'seo'));
    }

    public function showTag(Request $request, $tag)
    {
        //get banner home
        $banners = Banner::where('page', 'article')->get();

        $tag = str_replace('-', ' ', $tag);

        $tags = TaggableTag::tagslug($tag)->get();

        return view('frontend.article-tag', compact('banners', 'tags', 'tag'));
    }
}

app/Http/Controllers/Frontend/CartController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Tour;
use App\Banner;

class CartController extends Controller
{

    public function index()
    {
        return view('frontend.cart');
    }

    public function addToCart($id)
    {
        $tour = Tour::find($id);
    
        if(!$tour) {
    
            abort(404);
    
        }
    
        $cart = session()->get('cart');
    
        // if cart is empty then this the first product
        if(!$cart) {
    
            $cart = [
                    $id => [
                        "name" => $tour->title,
                        "quantity" => 1,
                        "price" => $tour->price,
                        "photo" => $tour->image
                    ]
            ];
    
            session()->put('cart', $cart);
    
            return redirect()->back()->with('success', 'Product added to cart successfully!');
        }
    
        // if cart not empty then check if this product exist then increment quantity
        if(isset($cart[$id])) {
    
            $cart[$id]['quantity']++;
    
            session()->put('cart', $cart);
    
            return redirect()->back()->with('success', 'Product added to cart successfully!');
    
        }
    
        // if item not exist in cart then add to cart with quantity = 1
        $cart[$id] = [
            "name" => $tour->title,
            "quantity" => 1,
            "price" => $tour->price,
            "photo" => $tour->image
        ];
    
        session()->put('cart', $cart);
    
        return redirect()->back()->with('success', 'Product added to cart successfully!');
    }

}

app/Http/Controllers/Frontend/ContactController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Contact;
use App\Banner;
use App\Page;

class ContactController extends Controller
{
    public function index(Request $request)
    {
        //get banner home
        $banners = Banner::page('contact')->get();

        $page  = Page::where('slug', 'contact-us')->active()->first();
        if (!$page) {
            abort(404);
        }
        return view('frontend.contact-us', compact('banners', 'page'));
    }

    public function store(Request $request)
    {
        $role = [
            'first_name' => 'required|max:255',
            'last_name'  => 'required|max:255',
            'phone'      => 'required',
            'email'      => 'required|email',
            'messenge'   => 'required',
        ];

        $messages = [
            'first_name.required' => 'กรุณาระบุชื่อ',
            'last_name.required'  => 'กรุณาระบุนามสกุล',
            'phone.required'      => 'กรุณาระบุเบอร์โทรศัพท์',
            'email.required'      => 'กรุณาระบุอีเมล',
            'messenge.required'   => 'กรุณาระบุข้อความ',
        ];

        $validator = Validator::make($request->all(), $role, $messages);

        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        }

        $contact             = new Contact;
        $contact->first_name = $request->first_name;
        $contact->last_name  = $request->last_name;
        $contact->phone      = $request->phone;
        $contact->email      = $request->email;
        $contact->messenge   = $request->messenge;
        $save = $contact->save();

        if ($save) {
            return back()->with([
                'message'    => 'ส่งข้อมูลเรียบร้อย',
                'alert-type' => 'success',
            ]);
        }
    }
}

app/Http/Controllers/Frontend/MainController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Service;
use App\Banner;
use App\Post;
use App\Tour;
use App\Page;
use App\Promotion;

class MainController extends Controller
{
    public function index()
    {
        //get banner home
        $banners = Banner::page('home')->get();
        //get service
        $services = Service::published()->where('featured', 1)
            ->offset(0)
            ->limit(6)
            ->order()
            ->get();

        //get post
        $posts = Post::published()
            ->publicat()
            ->where('featured', 1)
            ->offset(0)
            ->limit(3)
            ->order()
            ->get();


        //get Customer
        $tours_categories = Tour::order()
            ->with([
                'categorytour'
            ])
            ->whereNotIn('category_id', [1, 2])
            ->get()
            ->groupBy('categorytour.name');

        $promotions = Promotion::published()
            ->order()
            ->get();

        return view('frontend.home', compact('services', 'banners', 'posts', 'tours_categories', 'promotions'));
    }

    public function show(Request $request, $slug)
    {
    }
}

app/Http/Controllers/Frontend/PageController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class PageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function thank()
    {
        return view('frontend.page-thank');
    }

    public function fail()
    {
        return view('frontend.page-fail');
    }


}

app/Http/Controllers/Frontend/PromotionController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Promotion;
use App\Banner;

class PromotionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //get banner home
        $banners = Banner::page('promotion')->get();

        $promotions = Promotion::published()
            ->order()
            ->get();

        return view('frontend.promotions', compact('promotions', 'banners'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $slug)
    {
        //get banner home
        $banners = Banner::where('page', 'service')->get();

        //service
        $service = Service::where('slug', $slug)->published()->first();
        //SEO
        $seo = Service::select('seo_title', 'meta_description', 'image')->published()->where('slug', $slug)->first();
        if (!$service) {
            abort(404);
        }
        return view('frontend.service-detail', compact('banners', 'service', 'seo'));
    }
}

resources/views/frontend/about-us.blade.php
@extends('frontend.main')
@section('title', $article->title ?? setting('site.title'))
@section('seo')
@include('frontend.layouts.seo')
@if(setting('web-seo.sharethis'))
{!! setting('web-seo.sharethis') !!}
@endif
@stop
@section('navbar')
@include('frontend.layouts.navbar',['logo' => 'logo.png'])
@stop
@section('slides')
{{-- @include('frontend.slide.banner-video')  --}}
@isset($banners)
{{-- @include('frontend.slide.banner-image') --}}
@endisset
@stop
@section('content')
<main class="mt-5" style="margin-top: 10%!important">
    <div class="container">
        <section class="content">
            <h1 class="h3 text-left mb-3">เกี่ยวกับเรา</h1>
            @if($page->image)
            <div class="row">
                <div class="col-md-12 mb-5 mt-3">
                    <img src="{{ Voyager::image( $page->image) }}" class="img-fluid" alt="Responsive image">
                </div>
            </div>
            @endif
            <div class="row">
                <div class="col-md-12 mb-5 mt-3">
                    {!! $page->body !!}
                </div>
            </div>
        </section>
    </div>
</main>
@stop
@push('custom-scripts')
<script>
    $(".fancybox").fancybox();
</script>
@endpush
@section('footer')
@include('frontend.layouts.footer')
@stop

resources/views/frontend/article-detail.blade.php
@extends('frontend.main')
@section('title', $article->title ?? setting('site.title'))
@section('seo')
@include('frontend.layouts.seo')
@if(setting('web-seo.sharethis'))
{!! setting('web-seo.sharethis') !!}
@endif
@stop
@section('navbar')
@include('frontend.layouts.navbar',['logo' => 'logo.png'])
@stop
@section('slides')
{{-- @include('frontend.slide.banner-video')  --}}
@isset($banners)
@include('frontend.slide.banner-image')
@endisset
@stop
@section('content')
<main class="mt-5">
    <div class="container">
        <section class="content">
            <h1 class="h3 text-left mb-3">{{ $article->title }}</h1>
            <p class="category">หมวดหมู่ : {{ $article->category->name }}</p>
            <small class="post_date">โฟสเมื่อ : {{ DateThai($article->created_at)}}</small>
            <small class="read">อ่าน : {{ number_format($article->viewer + 1 ,0)}}</small>
            {{-- tag --}}
            <section class="mt-3">
                @foreach ($article->tagArray as $tag)
                <a href="{{ route('articles.tag',str_replace(' ','-',$tag))  }}" class="tag">{{ $tag }}</a>
                @endforeach
            </section>
            <div class="row">
                <div class="col-md-8 mb-5 mt-3">
                    <img src="{{ Voyager::image( $article->image) }}" class="img-fluid rounded-lg"
                        alt="{{ $article->title }}">
                    {{-- Share this --}}
                    @if(setting('web-seo.sharethis'))
                    <div class="my-4">
                        <div class="sharethis-inline-share-buttons"></div>
                    </div>
                    @endif
                    <div class="mt-2">
                        {!! $article->body !!}
                    </div>
                </div>
                <div class="col-md-4 mt-3">
                    @if(setting('contact.facebook_page'))
                    {!! setting('contact.facebook_page') !!}
                    @endif
                </div>
            </div>
        </section>
    </div>
</main>
@stop
@push('custom-scripts')
<script>
    $(".fancybox").fancybox();
</script>
@endpush
@section('footer')
@include('frontend.layouts.footer')
@stop

resources/views/frontend/home.blade.php
@extends('frontend.main')
@section('title', isset($title) ? $title : setting('site.title'))
@section('seo')
    @include('frontend.layouts.seo')
@stop

@section('navbar')
    @include('frontend.layouts.navbar',['logo' => 'logo.png'])
@stop
@section('slides')
    {{-- @include('frontend.slide.banner-video')  --}}
    @isset($banners)
        @include('frontend.slide.banner-image')
    @endisset
@stop
@section('content')
    <main class="">
        <!-- popular_courses_start -->
        <div class="popular_courses">
            {{--<div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="section_title text-center mb-4">
                            <h3>แพ็กเก็จทัวร์</h3>
                        </div>
                    </div>
                </div>
            </div>--}}
            <div class="all_courses">
                <div class="container">
                    @foreach ($tours_categories as $key => $tours)
                        <div class="row">
                            <div class="col-xl-12">
                                <div class="section_title text-left mb-4">
                                    <h4>{{ $key }}</h4>
                                </div>
                            </div>
                        </div>
                        @foreach ($tours as $i => $item)
                            @if($i ==0)
                                <div class="row">
                                    <div class="col-xl-12" style="height: 800px">
                                        <div class="section_title text-left mb-4">
                                            <img class="img-fluid"
                                                 src="{{ Voyager::image($item->categorytour->hero_image) }}">
                                        </div>
                                    </div>
                                </div>
                            @endif
                        @endforeach
                        <div class="row">
                            @foreach ($tours as $item)
                                <div class="col-xl-3 col-lg-3 col-md-4">
                                    <div class="single_courses">
                                        <div class="thumb">
                                            <a href="{{ route('tours.show',$item->slug) }}">
                                                <img src="{{ Voyager::image($item->thumbnail('medium')) }}"
                                                     alt="{{$item->title}}">
                                            </a>
                                        </div>
                                        <div class="courses_info">
                                            <div class="dotellipsis title">
                                                <h6 class="title-crad-display"><a
                                                        href="{{ route('tours.show',$item->slug) }}">{{ $item->title }}</a>
                                                </h6>
                                            </div>
                                            <div class="dotellipsis excerpt">
                                                <span>{{ $item->excerpt }}</span>
                                            </div>
                                            <div class="star_prise d-flex justify-content-between">
                                                @if(isset($item->discount) && (NOW() >= $item->promotion_start) && (NOW() <=
                                                       $item->promotion_end))
                                                    <div class="star promotion">

                                                        <span>โปรโมชั่น</span>
                                                        <div class="countdown"
                                                             data-countdown="{{ $item->promotion_end }}"></div>

                                                    </div>
                                                @endif
                                                <div class="prise">
                                                    @if(isset($item->discount) && (NOW() >= $item->promotion_start) && (NOW() <=
                                                        $item->promotion_end))
                                                        <span
                                                            class="offer">{{ number_format($item->price,0) }} บาท</span>
                                                        <p class="active_prise">
                                                            {{ number_format($item->discount,0) }} บาท
                                                        </p>
                                                    @else
                                                        <p class="active_prise">
                                                            {{ $item->price ? number_format($item->price,0) . 'บาท' : 'ยังไม่กำหนดราคา' }}
                                                        </p>
                                                    @endif
                                                </div>
                                            </div>
                                            <hr>
                                            <div class="row text-center">
                                                <div class="col-8">
                                                    <a href="{{ route('tours.show',$item->slug) }}"
                                                       class="genric-btn primary circle wfull">
                                                        รายละเอียด
                                                    </a>
                                                </div>
                                                <div class="col-4">
                                                    @guest
                                                        <a href="{{ route('login') }}">
                                                            @else
                                                                <a href="{{ route('tours.payment',$item->slug) }}">
                                                                    @endguest
                                                                    <img src="{{ url('/img/cart.png') }}" alt=""
                                                                         style="width: 40px;">
                                                                </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    @endforeach
                    <div class="col-xl-12">
                        <div class="more_courses text-center">
                            <a href="{{ route('tours.index') }}" class="genric-btn info-border circle">ดูทั้งหมด
                                <i
                                    class="fa fa-angle-double-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- popular_courses_end-->
        <!-- our_latest_blog_start -->
        @if(sizeof($promotions) > 0)
            <div class="our_latest_blog">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="section_title text-center mb-4">
                                <h3>โปรโมชั่นลดหนักมาก</h3>
                            </div>
                        </div>
                    </div>
                    <div class="row">

                        @foreach ($promotions as $promotion)
                            <div class="col-xl-4 col-md-4">
                                <div class="single_latest_blog">
                                    <div class="thumb">
                                        <img src="{{ Voyager::image($promotion->thumbnail('medium')) }}" alt="">
                                    </div>
                                    <div class="content_blog">
                                        <div class="date">
                                            <p>12 Jun, 2019 in <a href="#">Design tips</a></p>
                                        </div>
                                        <div class="blog_meta">
                                            <h3><a href="#">{{ $promotion->title }}</a></h3>
                                        </div>
                                        <div class="dot-ellipsis" style="height: 55px;color: rgb(113, 113, 113);">
                                            {!! $promotion->detail !!}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach

                    </div>
                </div>
            </div>
    @endif
    <!-- our_latest_blog_end -->
        <!-- subscribe_newsletter_Start -->

        <!-- subscribe_newsletter_end -->
    </main>
@stop
@push('custom-scripts')
    <script src="//cdn.rawgit.com/hilios/jQuery.countdown/2.2.0/dist/jquery.countdown.min.js"></script>
    <script>
        $('[data-countdown]').each(function () {
            var $this = $(this), finalDate = $(this).data('countdown');
            $this.countdown(finalDate, function (event) {
                if (event.strftime('%-D') == 0) {
                    $this.html(event.strftime('%H:%M:%S'));
                } else {
                    $this.html(event.strftime('%-D วัน  %H:%M:%S'));
                }
            });
        });
    </script>
@endpush
@section('footer')
    @include('frontend.layouts.footer')
@stop