routes/admin.php
<?php

Route::group( ['prefix' => 'admin'], function () {
    Voyager::routes();

    //roles update
    Route::match( ['put', 'patch'], 'my-roles/{role}', 'Voyager\VoyagerRoleController@update' )->name( 'voyager.roles.my-update' );
    //setting
    Route::get( '/websetting', 'Voyager\VoyagerSettingsController@websetting' )->name( 'websetting.index' );

    //summernote
    Route::post( 'summernote', 'Formfield\SummernoteController@upload' );

    //slug
    Route::post( '/check/check-dup-title/', ['uses' => 'CheckduptitleController@checkDupTitle'] )->name( 'check.check-dup-title' );

    Route::post( '/check/check-dup-slug/', ['uses' => 'CheckduptitleController@checkDupSlug'] )->name( 'check.check-dup-slug' );

    //memeber
    Route::get( '/members', 'MemberController@index' )->name( 'voyager.member.index' );
    Route::get( '/members/{id}/edit', 'MemberController@edit' )->name( 'voyager.member.edit' );
    Route::get( '/members/{id}', 'Voyager\VoyagerUserController@show' )->name( 'voyager.member.show' );
    Route::delete( '/members/{$id}', 'MemberController@destroy' )->name( 'voyager.member.destroy' );
    Route::put( '/members/{id}', 'Voyager\VoyagerUserController@update' )->name( 'voyager.member.update' );

    //group member
    Route::get( '/business-group', 'MemberController@businessGroup' )->name( 'voyager.business-group.index' );
    Route::get( '/business-group/{id}', 'MemberController@businessGroupShow' )->name( 'voyager.business-group.show' );
    //log Reader : admin/log-reader
    Route::group(
        [
            'namespace'  => '\Haruncpi\LaravelLogReader\Controllers',
            'middleware' => ['auth'],
        ],
        function () {
            Route::get( config( 'laravel-log-reader.view_route_path' ), 'LogReaderController@getIndex' );
            Route::post( config( 'laravel-log-reader.view_route_path' ), 'LogReaderController@postDelete' );
            Route::get( config( 'laravel-log-reader.api_route_path' ), 'LogReaderController@getLogs' );
        }
    );

    // order
    Route::match( ['post'], '/orders/{status}/{id}', [
        'as'   => 'order.changeStatus',
        'uses' => 'OrderController@changeOrder',
    ] );

    // transection
    Route::match( ['post'], '/transection/withdraw/{status}/{id}', [
        'as'   => 'transection.changeStatus',
        'uses' => 'TransectionController@changeStatus',
    ] );

} );

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::group( ['middleware' => ['referral']], function () {
    Route::get( '/', 'Frontend\MainController@index' )->name( 'home' );

    Route::group( ['middleware' => ['auth']], function () {
        Route::get( '/profile', 'Frontend\ProfileController@index' )->name( 'profile' );
        Route::get( '/profile/business', 'Frontend\ProfileController@business' )->name( 'profile.business' );
        Route::get( '/business/payment', 'Frontend\ProfileController@payment' )->name( 'business.payment' );

    } );

    Route::get( '/profile', 'Frontend\ProfileController@index' )->name( 'profile' );
    Route::get( '/profile/business', 'Frontend\ProfileController@business' )->name( 'profile.business' );
    Route::get( '/business/payment', 'Frontend\ProfileController@payment' )->name( 'business.payment' );
    Route::put( '/profile/{id}', 'Frontend\ProfileController@update' )->name( 'profile.update' );
    Route::put( '/business/update/{id}', 'Frontend\ProfileController@businessupdate' )->name( 'business.update' );

    Route::get( '/page/{slug}', 'Frontend\MainController@show' )->name( 'page' );

    Route::get( '/promotions', 'Frontend\PromotionController@index' )->name( 'promotions.index' );

    Route::get( '/tours', 'Frontend\ToursController@index' )->name( 'tours.index' );
    Route::get( '/tours/{slug}', 'Frontend\ToursController@show' )->name( 'tours.show' );

    Route::get( '/visa', 'Frontend\InsuranceController@visa' )->name( 'visa.index' );
    Route::get( '/visa/{slug}', 'Frontend\InsuranceController@show' )->name( 'visa.show' );

    Route::get( '/insurance', 'Frontend\InsuranceController@index' )->name( 'insurance.index' );
    Route::get( '/insurance/{slug}', 'Frontend\InsuranceController@show' )->name( 'insurance.show' );

    Route::group( ['middleware' => ['auth'], 'namespace' => 'Frontend'], function () {

        Route::group( ['as' => 'tours.'], function () {

            Route::match( ['get'], '/tours/payment/{slug}', [
                'as'   => 'payment',
                'uses' => 'ToursController@payment',
            ] );

            Route::match( ['post'], 'tours/payment/store', [
                'as'   => 'store',
                'uses' => 'OrdersController@store',
            ] );

            Route::match( ['put'], 'tours/payment/{id}/repay', [
                'as'   => 'repay',
                'uses' => 'OrdersController@repay',
            ] );

            Route::match( ['get', 'post'], 'tours/payment/paypal/success', [
                'as'   => 'paypal.success',
                'uses' => 'OrdersController@paypalSuccess',
            ] );

            Route::match( ['get'], 'tours/order/completed', [
                'as'   => 'thank',
                'uses' => 'PageController@thank',
            ] );

            Route::match( ['get'], 'tours/order/fail', [
                'as'   => 'fail',
                'uses' => 'PageController@fail',
            ] );

        } );

        Route::group( ['as' => 'insurance.'], function () {

            Route::match( ['get'], '/insurance/payment/{slug}', [
                'as'   => 'payment',
                'uses' => 'InsuranceController@payment',
            ] );

            Route::match( ['post'], 'insurance/payment/store', [
                'as'   => 'store',
                'uses' => 'InsuranceController@store',
            ] );

        } );

        Route::group( ['as' => 'member.'], function () {

            Route::match( ['get'], '/member/transection', [
                'as'   => 'income',
                'uses' => 'MemberController@income',
            ] );

            Route::match( ['post'], '/member/transection/withdraw', [
                'as'   => 'withdraw',
                'uses' => 'MemberController@withdraw',
            ] );

            Route::match( ['put'], '/member/transection/withdraw/update/{id}', [
                'as'   => 'withdraw.update',
                'uses' => 'MemberController@withdrawUpdate',
            ] );

            Route::match( ['get'], '/member/order', [
                'as'   => 'order',
                'uses' => 'OrdersController@index',
            ] );

            Route::match( ['get'], '/member/order/detail/{id}', [
                'as'   => 'order.detail',
                'uses' => 'OrdersController@show',
            ] );

        } );

    } );

    Route::get( '/cart', 'Frontend\CartController@index' )->name( 'cart.index' );
    Route::get( 'add-to-cart/{id}', 'Frontend\CartController@addToCart' );

    Route::get( '/services', 'Frontend\ServiceController@index' )->name( 'services.index' );
    Route::get( '/services/{slug}', 'Frontend\ServiceController@show' )->name( 'services.show' );

    Route::get( '/articles', 'Frontend\ArticleController@index' )->name( 'articles.index' );
    Route::get( '/articles/{slug}', 'Frontend\ArticleController@show' )->name( 'articles.show' );
    Route::get( '/articles/tag/{slug}', 'Frontend\ArticleController@showTag' )->name( 'articles.tag' );

    Route::get( '/about-us', 'Frontend\AboutusController@index' )->name( 'about-us.index' );

    Route::get( '/contact-us', 'Frontend\ContactController@index' )->name( 'contact-us.index' );
    Route::post( '/contact-us', 'Frontend\ContactController@store' )->name( 'contact-us.store' );

    Route::get( '/facebook/redirect', 'SocialAuthController@redirect' )->name( 'facebook.redirect' );
    Route::get( '/facebook/callback', 'SocialAuthController@callback' );

    Auth::routes();
} );

resources/views/menu/dropdown.blade.php
<li class="nav-item dropdown">
    @php
    if (Voyager::translatable($items)) {
    $items = $items->load('translations');
    }
    @endphp
    @foreach ($items as $menu_item)
    @php
    $originalItem = $menu_item;
    if (Voyager::translatable($menu_item)) {
    $menu_item = $menu_item->translate($options->locale);
    }
    $isActive = null;
    $styles = null;
    $icon = null;
    // Background Color or Color
    if (isset($options->color) && $options->color == true) {
    $styles = 'color:'.$menu_item->color;
    }
    if (isset($options->background) && $options->background == true) {
    $styles = 'background-color:'.$menu_item->color;
    }
    // Check if link is current
    if(url($menu_item->link()) == url()->current()){
    $isActive = 'active';
    }
    // Set Icon
    if(isset($options->icon) && $options->icon == true){
    $icon = '<i class="' . $menu_item->icon_class . '"></i>';
    }
    @endphp
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Dropdown</a>
    <div class="dropdown-menu">
        <a class="dropdown-item" href="#">Link 1</a>
        <a class="dropdown-item" href="#">Link 2</a>
        <a class="dropdown-item" href="#">Link 3</a>
    </div>
</li>
@endforeach
</li>

resources/views/menu/my_footer.blade.php
<div class="col-md-2 mb-3">
    <a class="" href="{{ url('/') }}">{{ 'หน้าแรก' }}
        <span class="sr-only">(current)</span>
    </a>
</div>
@php
if (Voyager::translatable($items)) {
$items = $items->load('translations');
}
@endphp
@foreach ($items as $menu_item)
@php
$originalItem = $menu_item;
if (Voyager::translatable($menu_item)) {
$menu_item = $menu_item->translate($options->locale);
}
$isActive = null;
$styles = null;
$icon = null;
// Background Color or Color
if (isset($options->color) && $options->color == true) {
$styles = 'color:'.$menu_item->color;
}
if (isset($options->background) && $options->background == true) {
$styles = 'background-color:'.$menu_item->color;
}
// Check if link is current
if(url($menu_item->link()) == url()->current()){
$isActive = 'active';
}
// Set Icon
if(isset($options->icon) && $options->icon == true){
$icon = '<i class="' . $menu_item->icon_class . '"></i>';
}
@endphp
@if(isset($isActive))
<div class="col-md-2 mb-3">
    <a class="{{$isActive}}" href="{{ $menu_item->link() }}">{{ $menu_item->title }}
        <span class="sr-only">(current)</span>
    </a>
</div>
@else
<div class="col-md-2 mb-3">
    <a class="" href="{{ $menu_item->link() }}">{{ $menu_item->title }}
    </a>
</div>
@endif
@if(!$originalItem->children->isEmpty())
@endif
@endforeach

resources/views/menu/my_menu.blade.php
<ul id="navigation">
    @php
    if (Voyager::translatable($items)) {
    $items = $items->load('translations');
    }
    @endphp
    @foreach ($items as $menu_item)
    @php
    $originalItem = $menu_item;
    if (Voyager::translatable($menu_item)) {
    $menu_item = $menu_item->translate($options->locale);
    }
    $isActive = null;
    $styles = null;
    $icon = null;
    // Background Color or Color
    if (isset($options->color) && $options->color == true) {
    $styles = 'color:'.$menu_item->color;
    }
    if (isset($options->background) && $options->background == true) {
    $styles = 'background-color:'.$menu_item->color;
    }
    // Check if link is current
    if(url($menu_item->link()) == url()->current()){
    $isActive = 'active';
    }
    if(url($menu_item->link()) == url('/').'/'.request()->segment(1)){
    $isActive = 'active';
    }
    // Set Icon
    if(isset($options->icon) && $options->icon == true){
    $icon = '<i class="' . $menu_item->icon_class . '"></i>';
    }
    @endphp
    @if(isset($isActive))
    <li><a class="{{$isActive}}" href="{{ $menu_item->link() }}">{{ $menu_item->title }}</a></li>
    @else
    <li><a class="" href="{{ $menu_item->link() }}">{{ $menu_item->title }}</a></li>
    @endif
    @if(!$originalItem->children->isEmpty())
    @endif
    @endforeach

    @guest
    <li>
        <a href="{{ route('login') }}">
        <!-- <a href="#test-form" class="login popup-with-form"> -->
            <i class="flaticon-user"></i>
            <span>เข้าสู่ระบบ</span>
        </a>
    </li>
    @else
    <li>
        <a href="#">
            <!-- <img src="" alt="" style="width: 30px;">&nbsp; -->
            <img src="{{ asset('img/user.png') }}" alt="" style="width: 30px;">
            {{ Auth::user()->name }}
            <i class="ti-angle-down"></i>
        </a>
        <ul class="submenu">
            <li>
                <a href="{{ url('profile') }}">
                    <i class="ti-user"></i>
                    <span>โปรไฟล์ส่วนตัว</span></a>
            </li>
            @if(Auth::user()->role()->pluck( 'name' )->contains( 'business' ))
            <li>
                <a href="{{ route('member.income') }}">
                    <i class="ti-money"></i>
                    <span>รายได้ของคุณ</span></a>
            </li>
            @endif
            <li>
                <a href="{{ route('member.order') }}">
                    <i class="ti-shopping-cart"></i>
                    <span>ประวัติการสั่งซื้อ</span></a>
            </li>
            <li>
                <a href="{{ route('logout') }}"
                    onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                    <i class="ti-share-alt"></i>&nbsp;<span>ออกจากระบบ</span>
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </li>
        </ul>
    </li>
    @endguest
</ul>